# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('created', models.DateField()),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=256)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='rssf',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rssf',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
