# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rssf', '0002_auto_20160705_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='image_url',
        ),
        migrations.AddField(
            model_name='feed',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='rssf',
            name='url',
            field=models.URLField(),
        ),
    ]
